services:
  - type: cron
    name: shop-app-inference
    runtime: python
    pythonVersion: 3.11
    plan: standard
    schedule: "0 2 * * *"
    rootDir: jobs
    buildCommand: pip install -r requirements.txt
    command: python run_inference.py
