import Link from "next/link";
import { all } from "../../../lib/db";

export const dynamic = "force-dynamic";

export default function PriorityQueuePage() {
  const queue = all(`
    SELECT
      o.order_id,
      o.order_datetime,
      o.order_total,
      o.fulfilled,
      c.customer_id,
      c.full_name AS customer_name,
      p.late_delivery_probability,
      p.predicted_late_delivery,
      p.prediction_timestamp
    FROM orders o
    JOIN customers c ON c.customer_id = o.customer_id
    JOIN order_predictions p ON p.order_id = o.order_id
    WHERE o.fulfilled = 0
    ORDER BY p.late_delivery_probability DESC, o.order_datetime ASC
    LIMIT 50
  `);

  return (
    <>
      <h1>Late Delivery Priority Queue</h1>
      <div className="msg-info mb-3">
        This queue shows unfulfilled orders ranked by their predicted probability of
        late delivery. Warehouse staff should prioritize orders at the top of this list
        to reduce late deliveries and improve customer satisfaction. Predictions are
        generated by an ML model — click <Link href="/scoring">Run Scoring</Link> to
        update them.
      </div>

      {queue.length === 0 ? (
        <p className="text-muted">
          No predictions available yet. <Link href="/scoring">Run scoring</Link> to
          generate predictions for unfulfilled orders.
        </p>
      ) : (
        <table>
          <thead>
            <tr>
              <th>Order</th>
              <th>Customer</th>
              <th>Order Date</th>
              <th className="text-right">Total</th>
              <th className="text-right">Late Prob</th>
              <th>Predicted Late</th>
              <th>Scored At</th>
            </tr>
          </thead>
          <tbody>
            {queue.map((row) => (
              <tr key={row.order_id}>
                <td>
                  <Link href={`/orders/${row.order_id}`}>#{row.order_id}</Link>
                </td>
                <td>{row.customer_name}</td>
                <td>{row.order_datetime}</td>
                <td className="text-right">${row.order_total.toFixed(2)}</td>
                <td className="text-right">
                  {(row.late_delivery_probability * 100).toFixed(1)}%
                </td>
                <td>
                  <span className={`badge ${row.predicted_late_delivery ? "badge-danger" : "badge-yes"}`}>
                    {row.predicted_late_delivery ? "Late" : "On Time"}
                  </span>
                </td>
                <td className="text-muted">{row.prediction_timestamp}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </>
  );
}
